name: CASPER DSP HDL CI

on:
  push:
    branches: [ master, dev]
  pull_request:
    branches: [ master ]

jobs:
  casper-dsp-build-and-test:
    name: CASPER DSP Modules Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run CASPER DSP Docker Compose Tests
        run: |
          cd container
          # Run the compose stack.
          # --abort-on-container-exit: stops Redis/Influx once pytest finishes
          # --exit-code-from test_runner: fails the CI job if pytest fails
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/results
